INSERT INTO book (id, title, author, description, image_url, available, genre, year, amount) VALUES
(1, 'Nekrosytuacje: Perełki z życia grabarza', 'Bailly Guillaume', 'A może tak rzucić wszystko i zostać grabarzem? Obcując na co dzień ze śmiercią, oswoić ją i uodpornić się na jej powagę, kosząc przy tym niezły hajs? Tak trzeba żyć!Podczas czytania tej książki przypominamy sobie najlepsze momenty z kultowego serialu "Sześć stóp pod ziemią". Lektura "Nekrosytuacji" wywołuje lekki dreszczyk, ożywczy śmiech i szczyptę kontemplacji. Wszystko w idealnych proporcjach, jak starannie skomponowane menu na stypie.',
 'https://www.ravelo.pl/pub/mm/img/220/100796547.jpg', 1, 'popularno-naukowa', 2019, 2),
(2, 'Tajemniczy przeciwnik', 'Christie Agatha', 'Mija kilka lat, ludzie usiłują się odnaleźć w powojennej rzeczywistości. Wśród nich są przyjaciele z dzieciństwa - zdemobilizowany Tommy Beresford i Prudence „Tuppence” Cowley, córka archidiakona. Ci dwoje wpadają na siebie przypadkiem. Wobec fatalnej sytuacji finansowej postanawiają założyć spółkę o szumnej nazwie Młodzi Łowcy Przygód i realizować zadania specjalne. Właściwie od razu otrzymują pierwsze zlecenie. Zostają zaangażowani przez brytyjski wywiad – muszą odnaleźć Jane Finn i powierzone jej dokumenty. Trzeba je zdobyć – inaczej ład Wielkiej Brytanii (a może i całego świata) będzie zagrożony. Gdyby treść dostała się do wiadomości publicznej, rząd byłby skompromitowany, a władzę na drodze przewrotu prawdopodobnie przejęliby komuniści. Młodzi Łowcy Przygód podejmują się wykonania zlecenia – będzie się działo! Porwania, pościgi, strzelaniny, zagadki, przebieranki…',
 'https://www.ravelo.pl/pub/mm/img/220/100082477.jpg', 1, 'kryminał', 2018, 2),
(3, 'Dziewczyna o siedmiu imionach', 'Lee Hyeonseo', 'Hyeonseo Lee, urodzona i wychowana w Korei Północnej, była jedną z milionów ludzi więzionych w granicach państwa, którym rządził brutalny komunistyczny reżim. Ponieważ mieszkała przy granicy z Chinami, miała nieco większy niż jej krajanie kontakt ze światem poza zamkniętym obszarem Samotnego Królestwa. Gdy w latach dziewięćdziesiątych XX wieku w Korei Północnej wybuchł głód, młoda dziewczyna zaczęła zastanawiać się nad tym, co widzi, zadawać pytania i powoli uświadamiać sobie, że przez całe życie poddawano ją głębokiej indoktrynacji. Niemożliwe było przecież, by takie represje, bieda i głód panowały w kraju, który – jak jej wmawiano – jest „najwspanialszy na świecie”.',
 'https://www.ravelo.pl/pub/mm/img/220/100366477.jpg', 1, 'popularno-naukowa', 2017, 4),
(4, 'Najlepiej dla wszystkich', 'Soukupová Petra', 'Niewielu jest żyjących pisarzy, po których każdą książkę gotowa jestem sięgać w ciemno, a spośród nich spora część uprawia gatunki niebeletrystyczne lub czytywane raczej dla rozrywki, niż wzbogacenia wiedzy o zawiłościach ludzkich uczuć i zachowań. Z zajmujących się tą ostatnią gałęzią literatury większości nie da się w żaden sposób zaliczyć do młodego pokolenia; czterdziestki nie przekroczyły tylko dwie panie: Celeste Ng i Petra Soukupová. Dwie poprzednie wydane w Polsce książki tej ostatniej – zbiór opowiadań „Zniknąć” i powieść „Pod śniegiem” – pozwoliły mi nabrać przekonania, że mimo stosunkowo młodego wieku jej twórczość cechuje się wszystkim tym, co mi w powieści psychologiczno-obyczajowej odpowiada: bliskością realnego życia, ostrością spojrzenia, umiejętnością oddawania emocji przeżywanych przez każdą postać, bez względu na to, czy to dziesięcioletni chłopiec, czy siedemdziesięcioletnia kobieta.',
 'https://www.ravelo.pl/pub/mm/img/220/100806205.jpg', 1, 'obyczajowa', 2015, 2),
(5, 'Płuczki: Poszukiwacze żydowskiego złota', 'Reszka Paweł Piotr', 'Czym jest „płuczka”? To słowo może nasuwać pewne skojarzenia, ale nie jest oczywiste. To miejsce, gdzie płukano kości, by łatwiej zauważyć złoto. To też symbol całego makabrycznego procederu – rozkopywania nieoznaczonych masowych grobów w miejscach kaźni Holocaustu (Bełżec, Sobibór, Treblinka), aby znaleźć kosztowności. Bo przecież „Żydzi byli bogate”[2]. I brali ze sobą wszystko, nie wiedząc, że jadą tam, gdzie przypieczętuje się ich los. Chowali pieniądze, złote zęby czy biżuterię. Choć zabierano im wszystko, zanim ich zabito, nie zawsze odnajdywano kosztowności. W rezultacie ofiary Holocaustu często trafiały do grobu razem z tymi skrzętnie schowanymi bogactwami. I to właśnie tych bogactw szukali… jak ich nazwać? Kopacze? Hieny cmentarne?',
 'https://www.ravelo.pl/pub/mm/img/220/100802248.jpg', 1, 'popularno-naukowa', 1999, 6),
(6, 'Morski ogień', 'Parker Natalie C.', 'Główna bohaterka o dostojnym imieniu Caledonia jest kapitanem statku "Mors Navis", którego załogę stanowią same kobiety, a właściwie młode dziewczyny. Można nazwać je buntowniczkami. Świat, który zamieszkują jest terroryzowany przez Arica Athaira. Nikczemny przywódca stworzył armię, która grabi i zabija. Armię tak potężną, że nie znalazł się dla niej równy przeciwnik. Każda z dziewcząt z Mors Navis wiele straciła przez Arica. Gdy tylko mają okazję, drobnymi czynami starają się osłabić armię tyrana.',
 'https://www.ravelo.pl/pub/mm/img/220/100799327.jpg', 1, 'fantastyka', 1995, 2),
(7, 'The Godfather', 'Mario Puzo', 'Dziewiętnastowieczny pisarz francuski – Honoré de Balzac powiedział kiedyś, że „za każdą wielką fortuną kryje się zbrodnia”*. W drugiej połowie dwudziestego wieku Mario Puzo – amerykański pisarz włoskiego pochodzenia napisał powieść, której mottem uczynił właśnie te słowa, i która stanowi ich swoistą ilustrację... O jakim dziele mowa? Oczywiście o „Ojcu chrzestnym”. Powieść błyskawicznie osiągnęła status bestsellera, a dziś wielu zalicza ją już do klasyki literatury światowej.',
 'https://www.ravelo.pl/pub/mm/img/220/100769352.jpg', 1, 'fabularna', 1992, 7),
(8, 'Wyloguj swój mózg', 'Hansen Anders', 'Ciekawe, czy w ogóle jest wśród nas ktoś taki, kto używa komórki wyłącznie do telefonowania i wysyłania smsów, no, ostatecznie jeszcze jako budzika i przypominajki? Ba, ale przecież nie po to kupuje się telefon za tyle-a-tyle, obdarzony tyloma-a-tyloma możliwościami, żeby korzystać z niego jak z jakiejś przedpotopowej „cegły z antenką”, nieprawdaż? Żeby, gdy się jest w obcym mieście, nie trzeba było po nim łazić z papierową mapą wielkości ręcznika, która i tak nam nie powie, w jakich godzinach otwarte są muzea i w której knajpce można zjeść najlepszą specjalność regionu; żeby za pomocą paru kliknięć można było wypożyczyć i uruchomić elektryczne auto lub hulajnogę, odebrać leki w aptece, podesłać koledze książkę albo promotorowi szkic pracy magisterskiej bez potrzeby pakowania do koperty i naklejania znaczka, zamówić do domu pizzę i posłuchać piosenki, której nie mamy na żadnej z posiadanych płyt. Przecież po to jest postęp techniczny, żeby z niego korzystać! To prawda.',
 'https://www.ravelo.pl/pub/mm/img/220/100855154.jpg', 1, 'naukowa', 2015, 3),
(9, 'Krótka historia prawie wszystkiego', 'Bryson Bill', 'Jesteśmy dopiero na samym początku tego wszystkiego. Sztuczka polega oczywiście na tym, ażeby nigdy nie znaleźć końca. A to niemal na pewno będzie wymagało znacznie więcej niż serii szczęśliwych przypadków"*. Tak kończy swoją "Krótką historię" niezwykle utalentowany dziennikarz, wielki popularyzator nauki i wiedzy o niej. Tej książki nie da się czytać jednym tchem, choć zapewne znajdą się tacy, którzy to uczynią. Tą książką trzeba się delektować, trzeba ją wchłaniać i często zastanawiać się nad jej treścią.',
'https://www.ravelo.pl/pub/mm/img/220/100492966.jpg', 1, 'naukowa', 2013, 4),
(10, 'Anna Karenina', 'Tołstoj Lew', 'Trudno pisać recenzję książki, która należy do klasyki światowej literatury i została uznana za arcydzieło, a fakt, że nie jestem wielkim znawcą XIX-wiecznej rosyjskiej prozy, odrobinę onieśmiela przy formułowaniu opinii i ocen, zwłaszcza tych krytycznych. Czuję jednak potrzebę, aby podzielić się moimi wrażeniami po przeczytaniu powieści. Wrażeniami, które w żadnym stopniu nie będą się opierać na dokonywanych przez dziesiątki lat analizach, krytykach, interpretacjach. Będzie to czysto subiektywna opinia człowieka, który lubi czytać.',
 'https://www.ravelo.pl/pub/mm/img/220/100163875.jpg', 1, 'romans', 1889, 8);

INSERT INTO user (id, login, password, role) VALUES
(1, 'd_user', '123', 'USER'),
(2, 'd_admin', '456', 'ADMIN');